### ISSUE TITLE
Run the code on localhost?

### ISSUE THREAD

**Issue by nikosalexakis** [abhinabsarkar/intranet-chat-bot#1]
Hi Abhinab,

I am trying to run the code on SFB Server 2015 (on-prem)and have some questions:
 1. Is it possible to run the code on the same server as SFB (localhost)?
 2. Do I have to run manually the UCWA autodiscovery & authentication process in order to get the values for the configuration (App.config --> LyncOAuthUrl, UCWAApplicationsUrl, UCWAApplicationsHost) ?
 
Thank you in advance!
Nikos

**Comment by abhinabsarkar** [comment]
Hello @nikosalexakis 

Apologies for the late response as I was travelling.
In case you are still looking for answer to the questions.

1. The code is basically a console application in this case. Yes, you can run it on the same server as SFB but I would not recommend this as it would hamper the ability to scale. Also, note that it is not tightly coupled with SFB as the interaction happens via APIs.

2. You don't necessarily have to run the discovery and authentication process manually. But if you are setting it up for a given enterprise, then that reduces the coding effort. In case you want to make it generic, it can be automated too.

**Comment by nikosalexakis** [comment]
Hi Abhinab,

Thank you for your response. 
1. I had problems running it on localhost, so I am running the code now on a separate VM.
2. I got the values by running it manually for now.

Could you please explain why the proxy is needed? The value is required in order to run the code.

Thanks again,
Nikos

**Comment by abhinabsarkar** [comment]
Hi Nikos,

Some enterprise require proxy to connect to internet from their intranet environment. If it is not the case for you, it can be ignored.

Thanks
Abhinab.

Sent from BlueMail<http://www.bluemail.me/r?b=12976>
On May 11, 2018, at 3:13 PM, Nikos Alexakis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Abhinab,

Thank you for your response.

  1.  I had problems running it on localhost, so I am running the code now from a separate VM.
  2.  I got the values by running it manually for now.

Could you please explain why the proxy is needed? The value is required in order to tun the code.

Thanks again,
Nikos

**Comment by nikosalexakis** [comment]
Ok Abhinab, 
Thanks for the prompt answer!
